version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: domino-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend-server
    ports:
      - "80:4000"
    environment:
      - PORT=4000
      - SERVER_ID=main-server
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./frontend:/usr/src/app/frontend 
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: